### ISSUE TITLE
Terminal Functionality

### ISSUE THREAD

**Issue by archishadatta** [uclaacm/linux-lab#109]
Todo:
- [x] mv
- [x] grep
- [x] find
- [x] chmod
- [x] cat with piping/redirection
- [x] longFormat for ``ls -l`` in globalTypes.ts
- [x] ``cp file1 file2 directoryPath``

**Comment by zhangjuliet** [comment]
Terminal won't let me enter after typing ``cp sourceFile destinationFile``

**Comment by jason2020** [comment]
Ah aiya, the old code containing functionality for that. Will be fixing that soon.

**Comment by bliutech** [comment]
Just realized we need to also implement `find`. Another command that's a bit tricky...

**Comment by bliutech** [comment]
Latest change breaks `clear` command. :(

<img width="795" alt="image" src="https://user-images.githubusercontent.com/67720812/210009728-7b4dea92-9641-47e0-8891-8354f36ebb97.png">

**Comment by bliutech** [comment]
@jason2020 ooo just found this after merging. I think the intended solution for the grep problem is `grep -R camera *` but grep currently doesn't support this.

**Comment by jason2020** [comment]
@bliutech Oh, good catch. I'll add in a tiny PR to support * (just treating it as no arg). I think the -R flag works now (cause I didn't check the case, so -r and -R are interchangeable).

**Comment by jason2020** [comment]
@bliutech How should the `ls -l` output look like? Cause we don't have inodes (yet aiya), so I'm unsure how to mockup the output. After #193 gets merged in, it should be very simple to implement the permissions output. But, printing out the number of links might be a bit of a challenge. Timestamps can just be uh `new Date()` lol.

**Comment by bliutech** [comment]
@jason2020 Let's simplify the output of `ls -l` for the purposes of this lab. Let's keep permissions, file owner, timestamps, and file name. We can drop the link count, group name, and file size for this iteration just to simplify (the lab doesn't talk really about any of these so I assume this simplification is acceptable for the learning process for now).
