### ISSUE TITLE
Terminal (styling)

### ISSUE THREAD

**Issue by archishadatta** [uclaacm/linux-lab#23]
The terminal will function as <div>'s with text on top of an input field. Use CSS to style these HTML elements to look like a terminal interface.

ex)
< div> ls </ div>
< div> cd .. </ div>
< input></ input>

**Comment by Weave-Trix** [comment]
Hi, please let me know if you still need help on this.

**Comment by Weave-Trix** [comment]
@zhangjuliet

**Comment by Weave-Trix** [comment]
@archishadatta

**Comment by zhangjuliet** [comment]
> Hi, please let me know if you still need help on this.

@Weave-Trix, just assigned you to ticket #27. To ensure that all devs have the chance to work on a ticket, we try to limit to one at a time. If you finish #27 early though, feel free to claim this if no one else has done so.
