### ISSUE TITLE
Side Navigation

### ISSUE THREAD

**Issue by archishadatta** [uclaacm/linux-lab#27]
Make a side navigation panel to navigate between the different page. The panel should open when the hamburger menu icon is pressed and there should be some way to close it. You may use any outside libraries you want.

**Comment by Weave-Trix** [comment]
Hi, I'm interested in working on this feature, do you still need help?

**Comment by zhangjuliet** [comment]
> Hi, I'm interested in working on this feature, do you still need help?

Hi @Weave-Trix, just assigned you to this ticket! Btw feel free to self-assign yourself to tickets in the future, no need to ask a PM :)
