### ISSUE TITLE
Nav buttons

### ISSUE THREAD

**Issue by archishadatta** [uclaacm/linux-lab#29]
On each page, create next and back buttons that navigate through the pages in the order shown in the [lo-fidelity mockup](https://www.figma.com/file/i6o0IuYh3YoVkzojsW1zaS/linux-learning-lab?node-id=0%3A1).

**Comment by Weave-Trix** [comment]
Hi, can i attempt on this?

**Comment by Weave-Trix** [comment]
@archishadatta
